/* Generated by wayland-scanner 1.22.0 */

/*
 * Copyright © 2018 Ilia Bozhinov
 * Copyright © 2020 Isaac Freund
 * Copyright © 2024 Victoria Brekenfeld
 *
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission.  The copyright holders make no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied
 * warranty.
 *
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
 * SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
 * THIS SOFTWARE.
 */

#include "wayland-util.h"

#include <stdint.h>
#include <stdlib.h>

#ifndef __has_attribute
#define __has_attribute(x) 0 /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface ext_foreign_toplevel_handle_v1_interface;
extern const struct wl_interface ext_workspace_handle_v1_interface;
extern const struct wl_interface wl_output_interface;
extern const struct wl_interface zcosmic_toplevel_handle_v1_interface;
extern const struct wl_interface zcosmic_workspace_handle_v1_interface;

static const struct wl_interface *cosmic_toplevel_info_unstable_v1_types[] = {
    NULL,
    &zcosmic_toplevel_handle_v1_interface,
    &ext_foreign_toplevel_handle_v1_interface,
    &zcosmic_toplevel_handle_v1_interface,
    &wl_output_interface,
    &wl_output_interface,
    &zcosmic_workspace_handle_v1_interface,
    &zcosmic_workspace_handle_v1_interface,
    &wl_output_interface,
    NULL,
    NULL,
    NULL,
    NULL,
    &ext_workspace_handle_v1_interface,
    &ext_workspace_handle_v1_interface,
};

static const struct wl_message zcosmic_toplevel_info_v1_requests[] = {
    {"stop", "", cosmic_toplevel_info_unstable_v1_types + 0},
    {"get_cosmic_toplevel", "2no", cosmic_toplevel_info_unstable_v1_types + 1},
};

static const struct wl_message zcosmic_toplevel_info_v1_events[] = {
    {"toplevel", "n", cosmic_toplevel_info_unstable_v1_types + 3},
    {"finished", "", cosmic_toplevel_info_unstable_v1_types + 0},
    {"done", "2", cosmic_toplevel_info_unstable_v1_types + 0},
};

WL_PRIVATE const struct wl_interface zcosmic_toplevel_info_v1_interface = {
    "zcosmic_toplevel_info_v1", 3, 2, zcosmic_toplevel_info_v1_requests, 3, zcosmic_toplevel_info_v1_events,
};

static const struct wl_message zcosmic_toplevel_handle_v1_requests[] = {
    {"destroy", "", cosmic_toplevel_info_unstable_v1_types + 0},
};

static const struct wl_message zcosmic_toplevel_handle_v1_events[] = {
    {"closed", "", cosmic_toplevel_info_unstable_v1_types + 0},
    {"done", "", cosmic_toplevel_info_unstable_v1_types + 0},
    {"title", "s", cosmic_toplevel_info_unstable_v1_types + 0},
    {"app_id", "s", cosmic_toplevel_info_unstable_v1_types + 0},
    {"output_enter", "o", cosmic_toplevel_info_unstable_v1_types + 4},
    {"output_leave", "o", cosmic_toplevel_info_unstable_v1_types + 5},
    {"workspace_enter", "o", cosmic_toplevel_info_unstable_v1_types + 6},
    {"workspace_leave", "o", cosmic_toplevel_info_unstable_v1_types + 7},
    {"state", "a", cosmic_toplevel_info_unstable_v1_types + 0},
    {"geometry", "2oiiii", cosmic_toplevel_info_unstable_v1_types + 8},
    {"ext_workspace_enter", "3o", cosmic_toplevel_info_unstable_v1_types + 13},
    {"ext_workspace_leave", "3o", cosmic_toplevel_info_unstable_v1_types + 14},
};

WL_PRIVATE const struct wl_interface zcosmic_toplevel_handle_v1_interface = {
    "zcosmic_toplevel_handle_v1", 3, 1, zcosmic_toplevel_handle_v1_requests, 12, zcosmic_toplevel_handle_v1_events,
};
