package loader

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"github.com/BurntSushi/toml"

	"github.com/y3owk1n/neru/internal/config"
	"github.com/y3owk1n/neru/internal/derrors"
)

// OverridePath returns the path to the override file derived from the given
// config path. For "config.toml" the override is "config.override.toml" in the
// same directory; for "my-neru.toml" it is "my-neru.override.toml", etc.
func OverridePath(path string) string {
	if path == "" {
		return ""
	}

	return strings.TrimSuffix(path, filepath.Ext(path)) + config.OverrideSuffix
}

// SaveOverride persists a nested map of overrides to a TOML file at the given
// path. The map should mirror the TOML section structure (e.g. {"hints": {"hint_characters": "abc"}}).
func SaveOverride(path string, overrides map[string]any) error {
	if len(overrides) == 0 {
		_, statErr := os.Stat(path)
		if statErr == nil {
			return os.Remove(path)
		}

		return nil
	}

	dir := filepath.Dir(path)

	mkdirErr := os.MkdirAll(dir, config.DefaultDirPerms)
	if mkdirErr != nil {
		return derrors.Wrap(
			mkdirErr,
			derrors.CodeConfigIOFailed,
			"failed to create override directory",
		)
	}

	var closeErr error

	file, fileErr := os.Create(path)
	if fileErr != nil {
		return derrors.Wrap(fileErr, derrors.CodeConfigIOFailed, "failed to create override file")
	}
	defer func() {
		cerr := file.Close()
		if cerr != nil && closeErr == nil {
			closeErr = derrors.Wrap(
				cerr,
				derrors.CodeConfigIOFailed,
				"failed to close override file",
			)
		}
	}()

	_, headerErr := fmt.Fprintln(file, "# Neru runtime config overrides")
	if headerErr != nil {
		return derrors.Wrap(
			headerErr,
			derrors.CodeConfigIOFailed,
			"failed to write override header",
		)
	}

	_, commentErr := fmt.Fprintln(
		file,
		"# Generated by `neru config set`. Edit or remove this file to revert changes.",
	)
	if commentErr != nil {
		return derrors.Wrap(
			commentErr,
			derrors.CodeConfigIOFailed,
			"failed to write override comment",
		)
	}

	_, blankErr := fmt.Fprintln(file)
	if blankErr != nil {
		return derrors.Wrap(
			blankErr,
			derrors.CodeConfigIOFailed,
			"failed to write override blank line",
		)
	}

	encodeErr := toml.NewEncoder(file).Encode(overrides)
	if encodeErr != nil {
		return derrors.Wrap(
			encodeErr,
			derrors.CodeSerializationFailed,
			"failed to encode overrides",
		)
	}

	return closeErr
}

// setNestedMapValue sets a value at a dotted path in a nested map.
func setNestedMapValue(data map[string]any, path string, value any) {
	parts := strings.Split(path, ".")

	current := data
	for i, part := range parts {
		if i == len(parts)-1 {
			current[part] = value

			return
		}

		next, ok := current[part].(map[string]any)
		if !ok {
			next = make(map[string]any)
			current[part] = next
		}

		current = next
	}
}

// deleteNestedMapValue removes a dotted-path key from a nested map. Empty
// ancestor maps are pruned so the serialized override file stays clean.
func deleteNestedMapValue(data map[string]any, path string) {
	parts := strings.Split(path, ".")
	if len(parts) == 0 || parts[0] == "" {
		return
	}

	// Walk down, collecting each level so we can prune on the way back up.
	stack := make([]map[string]any, 0, len(parts))
	stack = append(stack, data)

	current := data
	for i := range len(parts) - 1 {
		next, ok := current[parts[i]].(map[string]any)
		if !ok {
			return
		}

		stack = append(stack, next)
		current = next
	}

	// Delete the leaf key.
	delete(current, parts[len(parts)-1])

	// Prune empty ancestors from leaf upward.
	for i := len(stack) - 1; i > 0; i-- {
		if len(stack[i]) > 0 {
			break
		}

		delete(stack[i-1], parts[i-1])
	}
}

// getFieldValue reads a typed value from a Config by dotted path.
func getFieldValue(cfg *config.Config, path string) (any, error) {
	parts := strings.Split(path, ".")
	if len(parts) == 0 || parts[0] == "" {
		return nil, derrors.New(derrors.CodeInvalidConfig, "config path cannot be empty")
	}

	target := reflect.ValueOf(cfg).Elem()
	for partIdx, part := range parts {
		field := findFieldByTomlTag(target, part)
		if !field.IsValid() {
			return nil, derrors.Newf(
				derrors.CodeInvalidConfig,
				"unknown config field: %s (path element %q not found)",
				path,
				part,
			)
		}

		if partIdx == len(parts)-1 {
			return field.Interface(), nil
		}

		target = derefStruct(field)
		if target.Kind() != reflect.Struct {
			return nil, derrors.Newf(
				derrors.CodeInvalidConfig,
				"%q in path %q is not a struct",
				part,
				path,
			)
		}
	}

	return nil, derrors.Newf(derrors.CodeInvalidConfig, "path %q resolved to nil", path)
}
